# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rCommand.proto\x12\x16\x63n.csuosa.pojo.command\"\xfd\x02\n\x0b\x43ommandPOJO\x12@\n\toperation\x18\x01 \x01(\x0e\x32-.cn.csuosa.pojo.command.CommandPOJO.Operation\x12/\n\x04user\x18\x02 \x01(\x0b\x32\x1c.cn.csuosa.pojo.command.UserH\x00\x88\x01\x01\x12\x35\n\x07message\x18\x03 \x01(\x0b\x32\x1f.cn.csuosa.pojo.command.MessageH\x01\x88\x01\x01\x12\x35\n\x07\x63hannel\x18\x04 \x01(\x0b\x32\x1f.cn.csuosa.pojo.command.ChannelH\x02\x88\x01\x01\"l\n\tOperation\x12\t\n\x05LOGIN\x10\x00\x12\n\n\x06LOGOUT\x10\x01\x12\x10\n\x0cJOIN_CHANNEL\x10\x02\x12\x10\n\x0cQUIT_CHANNEL\x10\x03\x12\x08\n\x04SEND\x10\x04\x12\x0b\n\x07RECEIVE\x10\x05\x12\r\n\tHEARTBEAT\x10\x06\x42\x07\n\x05_userB\n\n\x08_messageB\n\n\x08_channel\"\x14\n\x04User\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"6\n\x07\x43hannel\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x11\n\x04nick\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_nick\"+\n\x07Message\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\tB\x1b\n\x0e\x63n.csuosa.pojoB\x07\x43ommandH\x01\x62\x06proto3')



_COMMANDPOJO = DESCRIPTOR.message_types_by_name['CommandPOJO']
_USER = DESCRIPTOR.message_types_by_name['User']
_CHANNEL = DESCRIPTOR.message_types_by_name['Channel']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_COMMANDPOJO_OPERATION = _COMMANDPOJO.enum_types_by_name['Operation']
CommandPOJO = _reflection.GeneratedProtocolMessageType('CommandPOJO', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDPOJO,
  '__module__' : 'Command_pb2'
  # @@protoc_insertion_point(class_scope:cn.csuosa.pojo.command.CommandPOJO)
  })
_sym_db.RegisterMessage(CommandPOJO)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'Command_pb2'
  # @@protoc_insertion_point(class_scope:cn.csuosa.pojo.command.User)
  })
_sym_db.RegisterMessage(User)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), {
  'DESCRIPTOR' : _CHANNEL,
  '__module__' : 'Command_pb2'
  # @@protoc_insertion_point(class_scope:cn.csuosa.pojo.command.Channel)
  })
_sym_db.RegisterMessage(Channel)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'Command_pb2'
  # @@protoc_insertion_point(class_scope:cn.csuosa.pojo.command.Message)
  })
_sym_db.RegisterMessage(Message)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016cn.csuosa.pojoB\007CommandH\001'
  _COMMANDPOJO._serialized_start=42
  _COMMANDPOJO._serialized_end=423
  _COMMANDPOJO_OPERATION._serialized_start=282
  _COMMANDPOJO_OPERATION._serialized_end=390
  _USER._serialized_start=425
  _USER._serialized_end=445
  _CHANNEL._serialized_start=447
  _CHANNEL._serialized_end=501
  _MESSAGE._serialized_start=503
  _MESSAGE._serialized_end=546
# @@protoc_insertion_point(module_scope)
