# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eResponse.proto\x12\x17\x63n.csuosa.pojo.response\"\xdd\x01\n\x0cResponsePOJO\x12\x38\n\x04type\x18\x01 \x01(\x0e\x32*.cn.csuosa.pojo.response.ResponsePOJO.Type\x12\x31\n\x07message\x18\x02 \x03(\x0b\x32 .cn.csuosa.pojo.response.Message\x12\x34\n\x06result\x18\x03 \x01(\x0b\x32\x1f.cn.csuosa.pojo.response.ResultH\x00\x88\x01\x01\"\x1f\n\x04Type\x12\n\n\x06RESULT\x10\x00\x12\x0b\n\x07MESSAGE\x10\x01\x42\t\n\x07_result\"(\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"=\n\x07Message\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x10\n\x08\x66romNick\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\tB\x1c\n\x0e\x63n.csuosa.pojoB\x08ResponseH\x01\x62\x06proto3')



_RESPONSEPOJO = DESCRIPTOR.message_types_by_name['ResponsePOJO']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_RESPONSEPOJO_TYPE = _RESPONSEPOJO.enum_types_by_name['Type']
ResponsePOJO = _reflection.GeneratedProtocolMessageType('ResponsePOJO', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEPOJO,
  '__module__' : 'Response_pb2'
  # @@protoc_insertion_point(class_scope:cn.csuosa.pojo.response.ResponsePOJO)
  })
_sym_db.RegisterMessage(ResponsePOJO)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'Response_pb2'
  # @@protoc_insertion_point(class_scope:cn.csuosa.pojo.response.Result)
  })
_sym_db.RegisterMessage(Result)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'Response_pb2'
  # @@protoc_insertion_point(class_scope:cn.csuosa.pojo.response.Message)
  })
_sym_db.RegisterMessage(Message)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016cn.csuosa.pojoB\010ResponseH\001'
  _RESPONSEPOJO._serialized_start=44
  _RESPONSEPOJO._serialized_end=265
  _RESPONSEPOJO_TYPE._serialized_start=223
  _RESPONSEPOJO_TYPE._serialized_end=254
  _RESULT._serialized_start=267
  _RESULT._serialized_end=307
  _MESSAGE._serialized_start=309
  _MESSAGE._serialized_end=370
# @@protoc_insertion_point(module_scope)
