// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package cn.csuosa.pojo;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommandPOJOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.csuosa.pojo.command.CommandPOJO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cn.csuosa.pojo.command.CommandPOJO.Operation operation = 1;</code>
     * @return The enum numeric value on the wire for operation.
     */
    int getOperationValue();
    /**
     * <code>.cn.csuosa.pojo.command.CommandPOJO.Operation operation = 1;</code>
     * @return The operation.
     */
    cn.csuosa.pojo.Command.CommandPOJO.Operation getOperation();

    /**
     * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
     * @return The message.
     */
    cn.csuosa.pojo.Command.Message getMessage();
    /**
     * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
     */
    cn.csuosa.pojo.Command.MessageOrBuilder getMessageOrBuilder();

    /**
     * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
     * @return Whether the channel field is set.
     */
    boolean hasChannel();
    /**
     * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
     * @return The channel.
     */
    cn.csuosa.pojo.Command.Channel getChannel();
    /**
     * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
     */
    cn.csuosa.pojo.Command.ChannelOrBuilder getChannelOrBuilder();
  }
  /**
   * Protobuf type {@code cn.csuosa.pojo.command.CommandPOJO}
   */
  public static final class CommandPOJO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.csuosa.pojo.command.CommandPOJO)
      CommandPOJOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommandPOJO.newBuilder() to construct.
    private CommandPOJO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandPOJO() {
      operation_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CommandPOJO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommandPOJO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              operation_ = rawValue;
              break;
            }
            case 18: {
              cn.csuosa.pojo.Command.Message.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = message_.toBuilder();
              }
              message_ = input.readMessage(cn.csuosa.pojo.Command.Message.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(message_);
                message_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 26: {
              cn.csuosa.pojo.Command.Channel.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = channel_.toBuilder();
              }
              channel_ = input.readMessage(cn.csuosa.pojo.Command.Channel.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(channel_);
                channel_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_CommandPOJO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_CommandPOJO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.csuosa.pojo.Command.CommandPOJO.class, cn.csuosa.pojo.Command.CommandPOJO.Builder.class);
    }

    /**
     * Protobuf enum {@code cn.csuosa.pojo.command.CommandPOJO.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RETAIN = 0;</code>
       */
      RETAIN(0),
      /**
       * <code>LOGOUT = 1;</code>
       */
      LOGOUT(1),
      /**
       * <code>JOIN_CHANNEL = 2;</code>
       */
      JOIN_CHANNEL(2),
      /**
       * <code>QUIT_CHANNEL = 3;</code>
       */
      QUIT_CHANNEL(3),
      /**
       * <code>SEND = 4;</code>
       */
      SEND(4),
      /**
       * <code>RECEIVE = 5;</code>
       */
      RECEIVE(5),
      /**
       * <code>HEARTBEAT = 6;</code>
       */
      HEARTBEAT(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>RETAIN = 0;</code>
       */
      public static final int RETAIN_VALUE = 0;
      /**
       * <code>LOGOUT = 1;</code>
       */
      public static final int LOGOUT_VALUE = 1;
      /**
       * <code>JOIN_CHANNEL = 2;</code>
       */
      public static final int JOIN_CHANNEL_VALUE = 2;
      /**
       * <code>QUIT_CHANNEL = 3;</code>
       */
      public static final int QUIT_CHANNEL_VALUE = 3;
      /**
       * <code>SEND = 4;</code>
       */
      public static final int SEND_VALUE = 4;
      /**
       * <code>RECEIVE = 5;</code>
       */
      public static final int RECEIVE_VALUE = 5;
      /**
       * <code>HEARTBEAT = 6;</code>
       */
      public static final int HEARTBEAT_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Operation valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Operation forNumber(int value) {
        switch (value) {
          case 0: return RETAIN;
          case 1: return LOGOUT;
          case 2: return JOIN_CHANNEL;
          case 3: return QUIT_CHANNEL;
          case 4: return SEND;
          case 5: return RECEIVE;
          case 6: return HEARTBEAT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.csuosa.pojo.Command.CommandPOJO.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Operation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cn.csuosa.pojo.command.CommandPOJO.Operation)
    }

    private int bitField0_;
    public static final int OPERATION_FIELD_NUMBER = 1;
    private int operation_;
    /**
     * <code>.cn.csuosa.pojo.command.CommandPOJO.Operation operation = 1;</code>
     * @return The enum numeric value on the wire for operation.
     */
    @java.lang.Override public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.cn.csuosa.pojo.command.CommandPOJO.Operation operation = 1;</code>
     * @return The operation.
     */
    @java.lang.Override public cn.csuosa.pojo.Command.CommandPOJO.Operation getOperation() {
      @SuppressWarnings("deprecation")
      cn.csuosa.pojo.Command.CommandPOJO.Operation result = cn.csuosa.pojo.Command.CommandPOJO.Operation.valueOf(operation_);
      return result == null ? cn.csuosa.pojo.Command.CommandPOJO.Operation.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private cn.csuosa.pojo.Command.Message message_;
    /**
     * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public cn.csuosa.pojo.Command.Message getMessage() {
      return message_ == null ? cn.csuosa.pojo.Command.Message.getDefaultInstance() : message_;
    }
    /**
     * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
     */
    @java.lang.Override
    public cn.csuosa.pojo.Command.MessageOrBuilder getMessageOrBuilder() {
      return message_ == null ? cn.csuosa.pojo.Command.Message.getDefaultInstance() : message_;
    }

    public static final int CHANNEL_FIELD_NUMBER = 3;
    private cn.csuosa.pojo.Command.Channel channel_;
    /**
     * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
     * @return Whether the channel field is set.
     */
    @java.lang.Override
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
     * @return The channel.
     */
    @java.lang.Override
    public cn.csuosa.pojo.Command.Channel getChannel() {
      return channel_ == null ? cn.csuosa.pojo.Command.Channel.getDefaultInstance() : channel_;
    }
    /**
     * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
     */
    @java.lang.Override
    public cn.csuosa.pojo.Command.ChannelOrBuilder getChannelOrBuilder() {
      return channel_ == null ? cn.csuosa.pojo.Command.Channel.getDefaultInstance() : channel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (operation_ != cn.csuosa.pojo.Command.CommandPOJO.Operation.RETAIN.getNumber()) {
        output.writeEnum(1, operation_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getMessage());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getChannel());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (operation_ != cn.csuosa.pojo.Command.CommandPOJO.Operation.RETAIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operation_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMessage());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getChannel());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.csuosa.pojo.Command.CommandPOJO)) {
        return super.equals(obj);
      }
      cn.csuosa.pojo.Command.CommandPOJO other = (cn.csuosa.pojo.Command.CommandPOJO) obj;

      if (operation_ != other.operation_) return false;
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (hasChannel() != other.hasChannel()) return false;
      if (hasChannel()) {
        if (!getChannel()
            .equals(other.getChannel())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + operation_;
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      if (hasChannel()) {
        hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
        hash = (53 * hash) + getChannel().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.csuosa.pojo.Command.CommandPOJO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.csuosa.pojo.Command.CommandPOJO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.csuosa.pojo.Command.CommandPOJO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.csuosa.pojo.command.CommandPOJO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.csuosa.pojo.command.CommandPOJO)
        cn.csuosa.pojo.Command.CommandPOJOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_CommandPOJO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_CommandPOJO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.csuosa.pojo.Command.CommandPOJO.class, cn.csuosa.pojo.Command.CommandPOJO.Builder.class);
      }

      // Construct using cn.csuosa.pojo.Command.CommandPOJO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
          getChannelFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        operation_ = 0;

        if (messageBuilder_ == null) {
          message_ = null;
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (channelBuilder_ == null) {
          channel_ = null;
        } else {
          channelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_CommandPOJO_descriptor;
      }

      @java.lang.Override
      public cn.csuosa.pojo.Command.CommandPOJO getDefaultInstanceForType() {
        return cn.csuosa.pojo.Command.CommandPOJO.getDefaultInstance();
      }

      @java.lang.Override
      public cn.csuosa.pojo.Command.CommandPOJO build() {
        cn.csuosa.pojo.Command.CommandPOJO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.csuosa.pojo.Command.CommandPOJO buildPartial() {
        cn.csuosa.pojo.Command.CommandPOJO result = new cn.csuosa.pojo.Command.CommandPOJO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (messageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = messageBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (channelBuilder_ == null) {
            result.channel_ = channel_;
          } else {
            result.channel_ = channelBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.csuosa.pojo.Command.CommandPOJO) {
          return mergeFrom((cn.csuosa.pojo.Command.CommandPOJO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.csuosa.pojo.Command.CommandPOJO other) {
        if (other == cn.csuosa.pojo.Command.CommandPOJO.getDefaultInstance()) return this;
        if (other.operation_ != 0) {
          setOperationValue(other.getOperationValue());
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        if (other.hasChannel()) {
          mergeChannel(other.getChannel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.csuosa.pojo.Command.CommandPOJO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.csuosa.pojo.Command.CommandPOJO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int operation_ = 0;
      /**
       * <code>.cn.csuosa.pojo.command.CommandPOJO.Operation operation = 1;</code>
       * @return The enum numeric value on the wire for operation.
       */
      @java.lang.Override public int getOperationValue() {
        return operation_;
      }
      /**
       * <code>.cn.csuosa.pojo.command.CommandPOJO.Operation operation = 1;</code>
       * @param value The enum numeric value on the wire for operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperationValue(int value) {
        
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.csuosa.pojo.command.CommandPOJO.Operation operation = 1;</code>
       * @return The operation.
       */
      @java.lang.Override
      public cn.csuosa.pojo.Command.CommandPOJO.Operation getOperation() {
        @SuppressWarnings("deprecation")
        cn.csuosa.pojo.Command.CommandPOJO.Operation result = cn.csuosa.pojo.Command.CommandPOJO.Operation.valueOf(operation_);
        return result == null ? cn.csuosa.pojo.Command.CommandPOJO.Operation.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.csuosa.pojo.command.CommandPOJO.Operation operation = 1;</code>
       * @param value The operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperation(cn.csuosa.pojo.Command.CommandPOJO.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.csuosa.pojo.command.CommandPOJO.Operation operation = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperation() {
        
        operation_ = 0;
        onChanged();
        return this;
      }

      private cn.csuosa.pojo.Command.Message message_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.csuosa.pojo.Command.Message, cn.csuosa.pojo.Command.Message.Builder, cn.csuosa.pojo.Command.MessageOrBuilder> messageBuilder_;
      /**
       * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
       * @return The message.
       */
      public cn.csuosa.pojo.Command.Message getMessage() {
        if (messageBuilder_ == null) {
          return message_ == null ? cn.csuosa.pojo.Command.Message.getDefaultInstance() : message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
       */
      public Builder setMessage(cn.csuosa.pojo.Command.Message value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
       */
      public Builder setMessage(
          cn.csuosa.pojo.Command.Message.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
       */
      public Builder mergeMessage(cn.csuosa.pojo.Command.Message value) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              message_ != null &&
              message_ != cn.csuosa.pojo.Command.Message.getDefaultInstance()) {
            message_ =
              cn.csuosa.pojo.Command.Message.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
       */
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = null;
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
       */
      public cn.csuosa.pojo.Command.Message.Builder getMessageBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
       */
      public cn.csuosa.pojo.Command.MessageOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_ == null ?
              cn.csuosa.pojo.Command.Message.getDefaultInstance() : message_;
        }
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Message message = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.csuosa.pojo.Command.Message, cn.csuosa.pojo.Command.Message.Builder, cn.csuosa.pojo.Command.MessageOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.csuosa.pojo.Command.Message, cn.csuosa.pojo.Command.Message.Builder, cn.csuosa.pojo.Command.MessageOrBuilder>(
                  getMessage(),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }

      private cn.csuosa.pojo.Command.Channel channel_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.csuosa.pojo.Command.Channel, cn.csuosa.pojo.Command.Channel.Builder, cn.csuosa.pojo.Command.ChannelOrBuilder> channelBuilder_;
      /**
       * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
       * @return Whether the channel field is set.
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
       * @return The channel.
       */
      public cn.csuosa.pojo.Command.Channel getChannel() {
        if (channelBuilder_ == null) {
          return channel_ == null ? cn.csuosa.pojo.Command.Channel.getDefaultInstance() : channel_;
        } else {
          return channelBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
       */
      public Builder setChannel(cn.csuosa.pojo.Command.Channel value) {
        if (channelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          channel_ = value;
          onChanged();
        } else {
          channelBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
       */
      public Builder setChannel(
          cn.csuosa.pojo.Command.Channel.Builder builderForValue) {
        if (channelBuilder_ == null) {
          channel_ = builderForValue.build();
          onChanged();
        } else {
          channelBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
       */
      public Builder mergeChannel(cn.csuosa.pojo.Command.Channel value) {
        if (channelBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              channel_ != null &&
              channel_ != cn.csuosa.pojo.Command.Channel.getDefaultInstance()) {
            channel_ =
              cn.csuosa.pojo.Command.Channel.newBuilder(channel_).mergeFrom(value).buildPartial();
          } else {
            channel_ = value;
          }
          onChanged();
        } else {
          channelBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
       */
      public Builder clearChannel() {
        if (channelBuilder_ == null) {
          channel_ = null;
          onChanged();
        } else {
          channelBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
       */
      public cn.csuosa.pojo.Command.Channel.Builder getChannelBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getChannelFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
       */
      public cn.csuosa.pojo.Command.ChannelOrBuilder getChannelOrBuilder() {
        if (channelBuilder_ != null) {
          return channelBuilder_.getMessageOrBuilder();
        } else {
          return channel_ == null ?
              cn.csuosa.pojo.Command.Channel.getDefaultInstance() : channel_;
        }
      }
      /**
       * <code>optional .cn.csuosa.pojo.command.Channel channel = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.csuosa.pojo.Command.Channel, cn.csuosa.pojo.Command.Channel.Builder, cn.csuosa.pojo.Command.ChannelOrBuilder> 
          getChannelFieldBuilder() {
        if (channelBuilder_ == null) {
          channelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.csuosa.pojo.Command.Channel, cn.csuosa.pojo.Command.Channel.Builder, cn.csuosa.pojo.Command.ChannelOrBuilder>(
                  getChannel(),
                  getParentForChildren(),
                  isClean());
          channel_ = null;
        }
        return channelBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.csuosa.pojo.command.CommandPOJO)
    }

    // @@protoc_insertion_point(class_scope:cn.csuosa.pojo.command.CommandPOJO)
    private static final cn.csuosa.pojo.Command.CommandPOJO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.csuosa.pojo.Command.CommandPOJO();
    }

    public static cn.csuosa.pojo.Command.CommandPOJO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommandPOJO>
        PARSER = new com.google.protobuf.AbstractParser<CommandPOJO>() {
      @java.lang.Override
      public CommandPOJO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandPOJO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommandPOJO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommandPOJO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.csuosa.pojo.Command.CommandPOJO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChannelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.csuosa.pojo.command.Channel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string channel = 1;</code>
     * @return The channel.
     */
    java.lang.String getChannel();
    /**
     * <code>string channel = 1;</code>
     * @return The bytes for channel.
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <code>optional string nick = 2;</code>
     * @return Whether the nick field is set.
     */
    boolean hasNick();
    /**
     * <code>optional string nick = 2;</code>
     * @return The nick.
     */
    java.lang.String getNick();
    /**
     * <code>optional string nick = 2;</code>
     * @return The bytes for nick.
     */
    com.google.protobuf.ByteString
        getNickBytes();
  }
  /**
   * Protobuf type {@code cn.csuosa.pojo.command.Channel}
   */
  public static final class Channel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.csuosa.pojo.command.Channel)
      ChannelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Channel.newBuilder() to construct.
    private Channel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Channel() {
      channel_ = "";
      nick_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Channel();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Channel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              channel_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              nick_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_Channel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_Channel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.csuosa.pojo.Command.Channel.class, cn.csuosa.pojo.Command.Channel.Builder.class);
    }

    private int bitField0_;
    public static final int CHANNEL_FIELD_NUMBER = 1;
    private volatile java.lang.Object channel_;
    /**
     * <code>string channel = 1;</code>
     * @return The channel.
     */
    @java.lang.Override
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channel_ = s;
        return s;
      }
    }
    /**
     * <code>string channel = 1;</code>
     * @return The bytes for channel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICK_FIELD_NUMBER = 2;
    private volatile java.lang.Object nick_;
    /**
     * <code>optional string nick = 2;</code>
     * @return Whether the nick field is set.
     */
    @java.lang.Override
    public boolean hasNick() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string nick = 2;</code>
     * @return The nick.
     */
    @java.lang.Override
    public java.lang.String getNick() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nick_ = s;
        return s;
      }
    }
    /**
     * <code>optional string nick = 2;</code>
     * @return The bytes for nick.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNickBytes() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channel_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, channel_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nick_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channel_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, channel_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nick_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.csuosa.pojo.Command.Channel)) {
        return super.equals(obj);
      }
      cn.csuosa.pojo.Command.Channel other = (cn.csuosa.pojo.Command.Channel) obj;

      if (!getChannel()
          .equals(other.getChannel())) return false;
      if (hasNick() != other.hasNick()) return false;
      if (hasNick()) {
        if (!getNick()
            .equals(other.getNick())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel().hashCode();
      if (hasNick()) {
        hash = (37 * hash) + NICK_FIELD_NUMBER;
        hash = (53 * hash) + getNick().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.csuosa.pojo.Command.Channel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.csuosa.pojo.Command.Channel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.Channel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.csuosa.pojo.Command.Channel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.Channel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.csuosa.pojo.Command.Channel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.Channel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.csuosa.pojo.Command.Channel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.Channel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.csuosa.pojo.Command.Channel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.Channel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.csuosa.pojo.Command.Channel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.csuosa.pojo.Command.Channel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.csuosa.pojo.command.Channel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.csuosa.pojo.command.Channel)
        cn.csuosa.pojo.Command.ChannelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_Channel_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_Channel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.csuosa.pojo.Command.Channel.class, cn.csuosa.pojo.Command.Channel.Builder.class);
      }

      // Construct using cn.csuosa.pojo.Command.Channel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        channel_ = "";

        nick_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_Channel_descriptor;
      }

      @java.lang.Override
      public cn.csuosa.pojo.Command.Channel getDefaultInstanceForType() {
        return cn.csuosa.pojo.Command.Channel.getDefaultInstance();
      }

      @java.lang.Override
      public cn.csuosa.pojo.Command.Channel build() {
        cn.csuosa.pojo.Command.Channel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.csuosa.pojo.Command.Channel buildPartial() {
        cn.csuosa.pojo.Command.Channel result = new cn.csuosa.pojo.Command.Channel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nick_ = nick_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.csuosa.pojo.Command.Channel) {
          return mergeFrom((cn.csuosa.pojo.Command.Channel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.csuosa.pojo.Command.Channel other) {
        if (other == cn.csuosa.pojo.Command.Channel.getDefaultInstance()) return this;
        if (!other.getChannel().isEmpty()) {
          channel_ = other.channel_;
          onChanged();
        }
        if (other.hasNick()) {
          bitField0_ |= 0x00000001;
          nick_ = other.nick_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.csuosa.pojo.Command.Channel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.csuosa.pojo.Command.Channel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object channel_ = "";
      /**
       * <code>string channel = 1;</code>
       * @return The channel.
       */
      public java.lang.String getChannel() {
        java.lang.Object ref = channel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string channel = 1;</code>
       * @return The bytes for channel.
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        java.lang.Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string channel = 1;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string channel = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <code>string channel = 1;</code>
       * @param value The bytes for channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nick_ = "";
      /**
       * <code>optional string nick = 2;</code>
       * @return Whether the nick field is set.
       */
      public boolean hasNick() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string nick = 2;</code>
       * @return The nick.
       */
      public java.lang.String getNick() {
        java.lang.Object ref = nick_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nick = 2;</code>
       * @return The bytes for nick.
       */
      public com.google.protobuf.ByteString
          getNickBytes() {
        java.lang.Object ref = nick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nick = 2;</code>
       * @param value The nick to set.
       * @return This builder for chaining.
       */
      public Builder setNick(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nick = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNick() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nick_ = getDefaultInstance().getNick();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nick = 2;</code>
       * @param value The bytes for nick to set.
       * @return This builder for chaining.
       */
      public Builder setNickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        nick_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.csuosa.pojo.command.Channel)
    }

    // @@protoc_insertion_point(class_scope:cn.csuosa.pojo.command.Channel)
    private static final cn.csuosa.pojo.Command.Channel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.csuosa.pojo.Command.Channel();
    }

    public static cn.csuosa.pojo.Command.Channel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Channel>
        PARSER = new com.google.protobuf.AbstractParser<Channel>() {
      @java.lang.Override
      public Channel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Channel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Channel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Channel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.csuosa.pojo.Command.Channel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.csuosa.pojo.command.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string channel = 1;</code>
     * @return The channel.
     */
    java.lang.String getChannel();
    /**
     * <code>string channel = 1;</code>
     * @return The bytes for channel.
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code cn.csuosa.pojo.command.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.csuosa.pojo.command.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      channel_ = "";
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              channel_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.csuosa.pojo.Command.Message.class, cn.csuosa.pojo.Command.Message.Builder.class);
    }

    public static final int CHANNEL_FIELD_NUMBER = 1;
    private volatile java.lang.Object channel_;
    /**
     * <code>string channel = 1;</code>
     * @return The channel.
     */
    @java.lang.Override
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channel_ = s;
        return s;
      }
    }
    /**
     * <code>string channel = 1;</code>
     * @return The bytes for channel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channel_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, channel_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(channel_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, channel_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.csuosa.pojo.Command.Message)) {
        return super.equals(obj);
      }
      cn.csuosa.pojo.Command.Message other = (cn.csuosa.pojo.Command.Message) obj;

      if (!getChannel()
          .equals(other.getChannel())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.csuosa.pojo.Command.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.csuosa.pojo.Command.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.csuosa.pojo.Command.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.csuosa.pojo.Command.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.csuosa.pojo.Command.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.csuosa.pojo.Command.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.csuosa.pojo.Command.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.csuosa.pojo.Command.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.csuosa.pojo.Command.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.csuosa.pojo.command.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.csuosa.pojo.command.Message)
        cn.csuosa.pojo.Command.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.csuosa.pojo.Command.Message.class, cn.csuosa.pojo.Command.Message.Builder.class);
      }

      // Construct using cn.csuosa.pojo.Command.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        channel_ = "";

        content_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.csuosa.pojo.Command.internal_static_cn_csuosa_pojo_command_Message_descriptor;
      }

      @java.lang.Override
      public cn.csuosa.pojo.Command.Message getDefaultInstanceForType() {
        return cn.csuosa.pojo.Command.Message.getDefaultInstance();
      }

      @java.lang.Override
      public cn.csuosa.pojo.Command.Message build() {
        cn.csuosa.pojo.Command.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.csuosa.pojo.Command.Message buildPartial() {
        cn.csuosa.pojo.Command.Message result = new cn.csuosa.pojo.Command.Message(this);
        result.channel_ = channel_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.csuosa.pojo.Command.Message) {
          return mergeFrom((cn.csuosa.pojo.Command.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.csuosa.pojo.Command.Message other) {
        if (other == cn.csuosa.pojo.Command.Message.getDefaultInstance()) return this;
        if (!other.getChannel().isEmpty()) {
          channel_ = other.channel_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.csuosa.pojo.Command.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.csuosa.pojo.Command.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object channel_ = "";
      /**
       * <code>string channel = 1;</code>
       * @return The channel.
       */
      public java.lang.String getChannel() {
        java.lang.Object ref = channel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string channel = 1;</code>
       * @return The bytes for channel.
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        java.lang.Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string channel = 1;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string channel = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <code>string channel = 1;</code>
       * @param value The bytes for channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.csuosa.pojo.command.Message)
    }

    // @@protoc_insertion_point(class_scope:cn.csuosa.pojo.command.Message)
    private static final cn.csuosa.pojo.Command.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.csuosa.pojo.Command.Message();
    }

    public static cn.csuosa.pojo.Command.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.csuosa.pojo.Command.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_csuosa_pojo_command_CommandPOJO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_csuosa_pojo_command_CommandPOJO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_csuosa_pojo_command_Channel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_csuosa_pojo_command_Channel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_csuosa_pojo_command_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_csuosa_pojo_command_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto\022\026cn.csuosa.pojo.command\"" +
      "\304\002\n\013CommandPOJO\022@\n\toperation\030\001 \001(\0162-.cn." +
      "csuosa.pojo.command.CommandPOJO.Operatio" +
      "n\0225\n\007message\030\002 \001(\0132\037.cn.csuosa.pojo.comm" +
      "and.MessageH\000\210\001\001\0225\n\007channel\030\003 \001(\0132\037.cn.c" +
      "suosa.pojo.command.ChannelH\001\210\001\001\"m\n\tOpera" +
      "tion\022\n\n\006RETAIN\020\000\022\n\n\006LOGOUT\020\001\022\020\n\014JOIN_CHA" +
      "NNEL\020\002\022\020\n\014QUIT_CHANNEL\020\003\022\010\n\004SEND\020\004\022\013\n\007RE" +
      "CEIVE\020\005\022\r\n\tHEARTBEAT\020\006B\n\n\010_messageB\n\n\010_c" +
      "hannel\"6\n\007Channel\022\017\n\007channel\030\001 \001(\t\022\021\n\004ni" +
      "ck\030\002 \001(\tH\000\210\001\001B\007\n\005_nick\"+\n\007Message\022\017\n\007cha" +
      "nnel\030\001 \001(\t\022\017\n\007content\030\003 \001(\tB\033\n\016cn.csuosa" +
      ".pojoB\007CommandH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_csuosa_pojo_command_CommandPOJO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_csuosa_pojo_command_CommandPOJO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_csuosa_pojo_command_CommandPOJO_descriptor,
        new java.lang.String[] { "Operation", "Message", "Channel", "Message", "Channel", });
    internal_static_cn_csuosa_pojo_command_Channel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_csuosa_pojo_command_Channel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_csuosa_pojo_command_Channel_descriptor,
        new java.lang.String[] { "Channel", "Nick", "Nick", });
    internal_static_cn_csuosa_pojo_command_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_csuosa_pojo_command_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_csuosa_pojo_command_Message_descriptor,
        new java.lang.String[] { "Channel", "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
